version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # app:
  #   build: ./app
  #   container_name: facebook_scraper_app
  #   depends_on:
  #     - mongo
  #   volumes:
  #     - ./app:/app
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/

volumes:
  mongo_data:
